[Chore] Replace all worker_* with agent_*
NapthaAI/naptha-sdk pull request #54
Opened 2024-12-09 13:28 UTC by adi-kmt

Fixes [this](https://github.com/NapthaAI/naptha-sdk/issues/51#issue-2717846527) issue

2024-12-27 01:52 UTC, moarshy commented
LGTM. Again, once the `multiagent_chat` and `simple_chat_agent` are ready we can test both `multiagent_chat` and `random_number_agent` to  make sure all workd.

2024-12-27 02:08 UTC, moarshy requested changes

2024-12-27 02:08 UTC, moarshy commented on naptha_sdk/agent.py
> +        agent_node_url = self.orchestrator_run.agent_deployments[self.agent_index].agent_node_url
As pointed out [here](https://github.com/NapthaAI/multiagent_chat/pull/1#discussion_r1898185187), could you please take a look at this again?

2025-01-12 17:22 UTC, richardblythman approved these changes

2025-01-12 17:22 UTC, merged